### ISSUE TITLE
Anmerkung von Tangemann für die Doku

### ISSUE THREAD

**Issue by AnDoMu** [beyersdp/eHealth-Project#10]
Zukunftsvision: Die Position von den Rettunsgmitteln & -kräften etc. automatisch zu erfassen.

Dazu sollen wir Ideen in die Dokumentation schreiben.
--> Wie kann mas dahingehend erweitern? Verbesserungen für das bisherige System?

**Comment by beyersdp** [comment]
Prozess zur automatischen Erfassung von Rettungsmitteln und -kräften.
Jeder besitzt eine Handyapp (Authentifizierung mittels Funkruf, der in der lokalen DB schon gespeichert ist).
Diese App sendet regelmäßig eine GPS-Standort-Information über HTTPS.
Die Standort-Nachricht wird vom node.js Server empfangen und der Standort in der DB aktualisiert.

**Comment by beyersdp** [comment]
Passwörter nicht verschlüsselt
Verschiedene Browser machen andere Dinge

**Comment by beyersdp** [comment]
Großes Server Projekt, bessere Struktur nächstes Mal

**Comment by beyersdp** [comment]
Schlagwörter serverseitig berechnen und anbieten der häufigsten Wörter

**Comment by beyersdp** [comment]
In der Doku die Änderungen am Datenmodell herausstellen (im aktuellsten farblich markieren) und kurz berschreiben
