### ISSUE TITLE
offene Frage -->Modal für den Einsatzbeginn

### ISSUE THREAD

**Issue by AnDoMu** [beyersdp/eHealth-Project#14]
- soll auch hier sogleich ein START-Button für den Gesamteinsatz entstehen? Oder soll vielleicht einfach automatisch gestartet werden, sobald die Abfrage des Modals bearbeitet und gespeichert wurde?

Allerdings sind dann noch keine Einsatzkräfte etc. angelegt und die Karte ist auch noch nicht eingestellt.

Andererseits besteht die Gefahr, dass wenn es nicht automatisch gestartet wird, das Starten via externen Button an sich vergessen wird, vor lauter Einsatzkräfte etc. anglegen...

**Comment by beyersdp** [comment]
Würde sagen, so bald ein Einsatzleiter bestimmt wurde, startet der Gesamteinsatz
