### ISSUE TITLE
Mail Tangemann Gesamtdoku

### ISSUE THREAD

**Issue by beyersdp** [beyersdp/eHealth-Project#15]

**Comment by beyersdp** [comment]
Wann genau Abgabe? --> für das REF und die Doku: Freitag, 5. Juli 2019, 23:59

Änderungen nach der Präsentation?

Für die Präsentation:
- es gibt keine feste Vorlage/Anforderung (es können Punkte aus der Doku & dem Statusbericht verwendet werden)
- es soll "spannend" umgesetzt werden
- Länge ca. 25 min (nicht länger als 30min)

**Comment by AnDoMu** [comment]
- [x] screenshots (wenn alles fertig ist), um dies dann auch bei der Präsentation zeigen zu können (zusätzlich zur Demo) und für die Doku
- [x] Das Projekt (aus GitHub) zippen und mitabgeben
- [x] Bedienungsanleitung für Tangemann schreiben
