### ISSUE TITLE
Fragen bzw. Verbesserungsvorschläge:

### ISSUE THREAD

**Issue by AnDoMu** [beyersdp/eHealth-Project#16]
- muss man jedes Mal, wenn man das Modal zur Änderung der Führungsposition erneut aufmacht Speichern drücken, obwohl es davor beim Anlegen einmal gespeichert wurde? --> ansonsten ist der X-Button überflüssig bzw. irreführend--> denn beim Neuladen der Seite erscheint dieses dann immer wieder

- wenn man die Einsatzkräfte etc. oder Einsätze nicht richtig beendet/abschließt, dann führt es zu fälschlichen Einträgen bei einem erneuten Großeinsatz --> vielleicht wäre hier dann folgende Funktion sinnvoll: Beim Beenden des Gesamteinsatzes werden alle Einsätze automatisch abgeschlossen und für alle Kräfte etc. wird automatisch Schichtende eingetragen --> somit kann man's nicht ausversehen vergessen (oder eben es sollte noch ein Hinweis beim Beenden hineingeschrieben werden, was meinst du?)

- Sicherheits-pop-up-window für's Beenden der Schichten und für's Abschließen der Einsätze wäre sinnvoll --> weil wenn diese einmal beendet wurden kann man ja nicht mehr drauf zugreifen, oder?

**Comment by AnDoMu** [comment]
Hatte versuch das letzere zu Implementieren, allerdings zerschieße ich dabei deine bisherige Funktionalität..:/

**Comment by beyersdp** [comment]
Zu Punkt [1]: Wenn die Führungsposition / Kerndaten zum Gesamteinsatz geändert werden sollen (ausgewählt über Drop-Down Menü Funktionen), dann muss auch auf Speichern geklickt werden. **D.h. das X zum Schließen kann entfernt werden**

Zu Punkt [2]: Sehr guter Hinweis, werde ich implementieren, dass Beenden für alle Kräfte Schichtende bedeutet. Dafür werde ich auch einen Satz in der Alert-Message ergänzen.

Zu Punkt [3]: Würde ich im Anbetracht der Zeit weglassen, Fällt unter die Rubrik (Ausfall-)Sicherheit, welche wir ja schon in der Anforderungsanalyse ausgeklammert hatten

Habe Punkt [1],[2] in unsere ToDo Listen aufgenommen
