### ISSUE TITLE
Loginseite optisch noch etwas ansprechender gestaltet

### ISSUE THREAD

**Issue by beyersdp** [beyersdp/eHealth-Project#4]
Wie wird der leere Bereich links oder rechts genutzt?
- farbliche Balken
- Erklärungen
- oder ein Einsatzbild als Hintergrund, etwas ausgeblendet anzeigen

Das Drop-Down Menü muss schneller findbar sein.

**Comment by AnDoMu** [comment]
- Login Seite wurde optisch angepasst
- die Erklärungen sind noch offen (allerdings: niedrige Prio)
- für die Datenschutzerklärung (evtl. hilfreiche Links):
   - https://datenschutzerklärunggenerator.de/
   - https://datenschutz-generator.de/
